= Bases de Datos I: Prácticas
v2, {docdate}
:toc-title: Contenidos
:toc: left
:tabsize: 4
:icons: font
:source-highlighter: coderay
:note-caption: Nota
:figure-caption: Figura
:table-caption: Tabla
:pdf-page-size: A4
:pdf-page-margin: [3cm, 3cm, 3cm, 3cm]

== Práctica 1

=== Parte I: Diagrama Entidad Relación

*Modelar mediante un DER la situación planteada en cada ejercicio.*

. Una empresa vende productos a varies clientes. Se necesitan conocer
los datos personales de les clientes—i.e. nombre, apellido, DNI,
dirección, y fecha de nacimiento. Cada producto tiene un nombre y un
código, así como un precio unitario. Une cliente puede comprar varios
productos a la empresa, y un mismo producto puede ser comprado por
varies clientes. Los productos son suministrados por diferentes
proveedores. Se debe tener en cuenta que un producto sólo puede ser
suministrado por une proveedore, y que une proveedore puede suministrar
diferentes productos. De cada proveedore se desea conocer su CUIT,
nombre, y dirección.

. Una tienda de música desea modelar a les compositores de sinfonías, a
las sinfonías, y a la relación entre ambes. De les compositores se
conoce su nombre y su fecha de nacimiento, mientras que de cada sinfonía
se conoce el nombre de su compositore, el género, la tonalidad, y los
distintos instrumentos que se utilizan para su ejecución.

. La panadería y confitería "El Churro de Chocolate" está organizando el
delivery a sus clientes, para ello han dividido la ciudad en zonas.
Cada zona tiene un nombre que la identifica. Cada cliente pertenece a
una zona.  Les repartidores tienen asignades clientes, cada cliente
puede ser atendide por más de une repartidore, ó por ningune. A cada
zona se le asigna une repartidore como jefe de esa zona. Une repartidore
puede ser jefe de varias zonas ó de ninguna. De les repartidores se
conoce el nombre y legajo. De les clientes se conoce el nombre,
teléfono, dirección, y la fecha de la primera compra.

. Modificar el DER anterior para que se pueda registrar cada vez que se
realiza una entrega a domicilio, le repartidore que la realizó, la fecha
y hora de la entrega y el monto pagado por le cliente.

. La cadena de restaurantes "La Angioplastía" ha relevado información
acerca de les clientes y de sus preferencias. De cada persona,
identificada por su documento de identidad, se conoce su nombre, el
restaurante que más frecuenta, y las comidas que más le gustan. De cada
restaurante, identificado por su nombre, se conocen las comidas que
preparan. De cada comida se conoce el nombre que la identifica, el
tiempo de preparación, y los ingredientes que lleva y en qué cantidades.
De los ingredientes se conoce, nombre, proveedore, precio, y unidad en
la que está expresado el precio.

. Modificar el DER anterior considerando los siguientes cambios:

 - Una persona frecuenta varios restaurantes.

 - A una persona no le gusta una comida por si sola, sino que le gusta
  como la sirven en determinados restaurantes.

. La cooperativa de payases "Berumoddo" coordina las actuaciones de sus
payases integrantes. Les payases tienen sus propias actuaciones—pueden
tener más de una. De les payases se conoce su nombre y edad. Cada
actuación pertenece a une únique payase y se pone en escena en un circo.
De acuerdo al convenio que firmó, la cooperativa con la "Asociación de
Circos Peronistas", las actuaciones son exclusivas para cada circo, pero
en cada circo puede haber más de una actuación, aún correspondiente a
distintes payases. Cada actuación tiene un nombre y un precio de
entrada. Cada circo tiene un nombre, y una fecha de fundación.

. El Registro Civil de las Personas, desea llevar un registro de todas
las personas. De cada persona se conoce su primer y segundo nombre, su
apellido, su fecha de nacimiento, y su número de DNI. También se desea
llevar registro acerca de quienes se han casado, y con quién.
Adicionalmente, se desea llevar un registro de quienes son les xadres
biológiques de cada persona, y eventualmente, de quienes son les xadres
adoptives.

. La veterinaria "Pet Shop of Horrors" necesita llevar un control
informatizado de su gestión. De cada animal—ó paciente—se desea guardar
el código, el nombre, el tipo de animal, la raza, y el año de
nacimiento. De cada dueñe de cada animal se desea guardar nombre,
apellido, dirección, y teléfono.
+
También, se desea llevar un control de cada una de las veces que se
atiende a une animal, registrando la fecha, el diagnostico, el
tratamiento, le veterinarie que le atendió, y el costo de la consulta.
La veterinaria tiene varies veterinaries, de les cuales se desea
registrar, su número de matrícula, fecha de ingreso, nombre y apellido.
+
Une veterinarie puede atender a varies animales, pero una consulta es
atendida por une únique veterinarie.
+
Adicionalmente, de les perres se desea guardar la fecha de su última
vacuna contra la rabia, y de les gates se desea registrar el color de su
pelaje.
+
Un problema adicional que tienen en esta veterinaria, es que suele
suceder que les animales que están siendo atendides, ante una
distracción de les veterinaries, se pelean entre elles, y les
veterinaries por temor a lastimarse elles mismes no les separan. Le
propietarie de la veterinaria ha puesto un premio para cada veterinarie
que separa a les animales que se pelean. Por lo tanto, se desean
registrar les animales que participaron en la pelea, y le veterinarie
que les separo.

. El Ministerio de Salud desea mantener un sistema de información
relativo a los hospitales. A continuación, se detalla lo que se desea
modelar:

 - *hospital* con los datos: código que lo identifica, nombre,
   dirección, teléfono, y cantidad de camas.

 - *sala* con los datos: código, nombre, y cantidad de camas.

 - *médique* con los datos: DNI, nombre, y especialidad.

 - *laboratorio* con los datos: código que lo identifica, nombre,
   dirección, teléfono.

 - *paciente* con los datos: DNI, número de historia clínica, número de
   cama, nombre, dirección, fecha de nacimiento, y sexo.

 - *diagnóstico* con los datos: código que lo identifica, tipo, y
   complicaciones.

+
Además, sabemos que:

- Cada hospital tiene varias salas. Cada una de ellas pertenece a un
  solo hospital. En distintos hospitales pueden haber salas con el mismo
  código, pero esto no puede ocurrir dentro de un mismo hospital.

- Cada médique trabaja en un único hospital.

- Cada hospital trabaja con muchos laboratorios, y un laboratorio presta
  servicios a más de un hospital. Nos interesa conocer la descripción de
  cada servicio prestado por el laboratorio a un hospital, y la fecha en
  que se realizó.

- Une paciente puede estar internade en una única sala.

- Cada paciente puede ser atendide por más de une médique, y a su vez
  cada médique atenderá a varies pacientes. Nos interesa conocer las
  fechas de las atenciones.

- Cada paciente puede tener varios diagnósticos. Nos interesa saber la
  fecha en que se realizó cada uno.

//. Se desea realizar una base de datos geográfica. Los países pueden
//clasificarse en países independientes, y en colonias. Las colonias
//pertenecen a algún país independiente. Estos últimos tienen alguna forma
//de gobierno que puede ser: república, principado, emirato, democracia
//popular, dictadura, etc. Los países independientes comercian entre sí
//distintos productos. Las colonias sólo comercian con el país
//colonizador. En ambos casos, del producto comerciado se conoce un código
//que lo identifica, y el nombre. Las relaciones de comercio posibles son
//de importación y de exportación de productos. También forma parte de la
//base de datos la información de los límites entre países—i.e. qué países
//limitan con un país dado.

//. Completar el DER del punto anterior, considerando lo siguiente.
//También interesa modelar información relativa a los ríos, los cuales
//pueden ser internacionales ó nacionales. Los ríos internacionales sirven
//de límite entre dos países, mientras que los nacionales están totalmente
//contenidos en un solo país. Los datos que interesan de cada río son su
//nombre, caudal, y longitud. Se supone que pueden existir dos ríos
//nacionales con igual nombre en distinto país. Los ríos internacionales
//tienen nombre único.

=== Parte II: Modelo Relacional

*Pasar todos los ejercicios de la Parte I al modelo relacional.*

== Práctica 2

=== Parte I: Dependencias Funcionales

1. Dadas las siguientes relaciones, indicar cuáles son las dependencias
funcionales no triviales que se deberían cumplir.

a. alumne(nro_legajo, nombre, apellido, dni, carrera, materia,
nota_final).

b. empleade(legajo, nombre, apellido, dpto, legajo_jefe_dpto, f_ingreso,
salario).

2. Dada la relación
+
artículo(cod, descr, costo, precio, stock, prov)
+
y conjunto de dependencias funcionales
+
_F_ = {cod → descr stock, cod prov → costo, costo → precio, descr → cod},
+
indicar cuales de las siguientes dependencias funcionales se pueden
deducir de _F_ usando los axiomas de Armstrong. En caso de que no se
puedan deducir, demostrar mediante una instancia de la relación artículo
que sirva de contraejemplo.

a. cod prov → descr precio

b. cod → precio

c. descr → stock

d. precio → costo

e. descr prov → cod descr costo precio stock prov

3. Dada la relación _R(A, B, C, D, E)_. Cuáles de las siguientes
inferencias son válidas? Demostrar la validez de cada una usando las
reglas de Armstrong, en caso contrario encontrar algún contraejemplo.

a. { _A_ → _BC_, _C_ → _DE_ } ⊨ { _A_ → _ABCDE_ }

b. { _A_ → _B_, _B_ → _C_, _C_ → _D_ } ⊨ { _B_ → _A_ }

c. { _A_ → _B_, _B_ → _C_, _C_ → _D_, _D_ → _A_ } ⊨ { _B_ → _A_ }

d. { _A_ → _B_, _BD_ → _C_ } ⊨ { _AD_ → _BC_ }

e. { _AB_ → _C_, _C_ → _D_, _BD_ → _E_ } ⊨ { _A_ → _ABCDE_ }

4. Demostrar las reglas de descomposición y de pseudo transitividad usando las
reglas de Armstrong.

5. Hallar la clausura de atributos para cada uno de los siguientes
conjuntos de dependencias funcionales, considerando la relación
_R(X, Y, Z, S, T, U, V, W)_:

a. Dado { _X_ → _YT_, _YW_ → _Z_, _TZ_ → _U_, _U_ → _V_ }, obtener _XW⁺_
y _X⁺_.

b. Dado { _X_ → _Y_, _YW_ → _Z_, _TZ_ → _U_, _U_ → _V_ }, obtener _XW⁺_
y _XWT⁺_.

c. Dado { _X_ → _Y_, _YW_ → _Z_, _TZ_ → _U_, _U_ → _V_, _V_ → _X_ },
obtener _U⁺_, _UW⁺_ y _W⁺_.

d. Dado { _X_ → _U_, _YW_ → _V_, _TZ_ → _U_, _U_ → _V_, _V_ → _W_, _S_ →
_TV_, _T_ → _X_ }, obtener _XY⁺_, _S⁺_ y _ST⁺_.

6. Dada la relación _R(A, B, C, D, E, H)_, demostrar que los siguientes
conjuntos de dependencias funcionales son equivalentes entre sí.
+
_F_ = { _A_ → _C_, _AC_ → _D_, _E_ → _AD_, _E_ → _H_ }
+
_G_ = { _A_ → _CD_, _E_ → _AH_ }

7. Dada la relación _R(A, B, C, D, E, F, G, H)_, hallar el cubrimiento
minimal de los siguientes conjuntos de dependencias funcionales, e
indicar cuáles de ellos son equivalentes entre sí.

a. { _A_ → _ABE_, _C_ → _D_, _E_ → _FG_, _AD_ → _EFG_ }

b. { _A_ → _BE_, _C_ → _D_, _E_ → _F_, _E_ → _G_, _AD_ → _EF_ }

c. { _A_ → _BE_, _B_ → _D_, _C_ → _D_, _E_ → _EFG_, _A_ → _BEF_ }

d. { _A_ → _BE_, _CH_ → _D_, _E_ → _F_, _E_ → _G_, _AD_ → _EF_ }

e. { _A_ → _BE_, _C_ → _DC_, _E_ → _EFG_, _E_ → _G_, _AD_ → _EFG_ }

=== Parte II: Formas Normales

1. Dada la relación _R(A, B, C, D, E)_ encontrar *todas* las claves de
_R_ con respecto a los siguientes conjuntos de dependencias funcionales.

a. { _A_ → _BC_, _C_ → _DE_ }

b. { _A_ → _B_, _B_ → _C_, _C_ → _D_ }

c. { _A_ → _B_, _B_ → _C_, _C_ → _D_, _D_ → _A_ }

d. { _A_ → _B_, _BD_ → _C_ }

e. { _AB_ → _C_, _C_ → _D_, _BD_ → _E_ }

2. Sea _R(A, B, C, D, E, F)_ y el conjunto de dependencias funcionales
_F_ = { _A_ → _CB_, _A_ → _F_, _C_ → _E_, _D_ → _E_, _F_ → _A_ }. Hallar
*todas* las claves—y ver que son minimales.

3. Sea la relación _R(A, B, C, D, E, F)_ y el conjunto de dependencias
funcionales F = { _A_ → _BC_, _A_ → _F_, _C_ → _E_, _D_ → _E_, _F_ → _A_
}.

a. Hallar las claves de _R_.

b. Decir en qué forma normal se encuentra _R_. Justificar.

4. Sea la relación _R(A, B, C, D, E, F, G, H, I)_ y el conjunto de
dependencias funcionales F = { _A_ → _BC_, _A_ → _F_, _C_ → _E_, _CD_ →
_EI_, _F_ → _GH_ }.

a. Hallar las claves de _R_.

b. Decir en qué forma normal se encuentra _R_. Justificar.

5. Dada la siguiente relación con su conjunto de dependencias
funcionales:
+
f1(pilote, escudería, circuito, cant_vueltas, long_circuito, año,
posición, tiempo)
+
pilote circuito año → posición tiempo
+
circuito → long_circuito
+
circuito año → cant_vueltas
+
pilote año → escudería
+
Indicar en qué forma normal se encuentra la relación f1.

6. Utilizando las dependencias funcionales que se identificaron en el
*Ejercicio 1b de Dependencias Funcionales*, indicar en que forma normal
se encuentra la relación empleade.

7. Hallar las claves e indicar en qué forma normal se encuentra la
relación _R(A, B, C, D, E, F, G)_ con respecto a los siguientes
conjuntos de dependencias funcionales:

a. F = { _A_ → _C_, _B_ → _D_, _E_ → _F_, _A_ → _G_ }.

b. F = { _A_ → _C_, _B_ → _D_, _B_ → _F_, _A_ → _G_, _A_ → _B_, _A_ →
_E_ }.

c. F = { _A_ → _C_, _B_ → _D_, _B_ → _F_, _A_ → _G_, _A_ → _B_ }.

d. F = { _ABE_ → _CDFG_, _E_ → _A_ }.

8. Para los ítems del *Ejercicio 7 de Dependencias Funcionales*,
descomponer a BCNF.

9. Descomponer a 3NF las relaciones de los *Ejercicios 3 y 4*.

== Práctica 3

=== Parte I: Álgebra Relacional

1. Dadas las siguientes relaciones, resolver usando álgebra relacional.
+
bote([underline]#bid#, nombre, color)
+
marine([underline]#mid#, nombre, puntaje, f_inscripcion)
+
alquiler([underline]#bid, mid, fecha#)
+
reserva([underline]#bid, mid, fecha#)

a. Obtener los nombres de los botes rojos.

b. Obtener los nombres de les marines que se inscribieron después del
2011-06-26.

c. Obtener los nombres de les marines que se inscribieron durante el año
2012.

d. Obtener los bid's de los botes alquilados por le marine número 3.

e. Obtener los nombres de les marines que alquilaron el bote "Macross".

f. Obtener los nombres de les marines que alquilaron botes rojos.

g. Obtener los botes reservados para el 2011-06-26.

h. Obtener los botes disponibles para alquilar el 2011-06-26.

i. Obtener los nombres de les marines que no alquilaron ningún bote.

j. Obtener los nombres de les marines que alquilaron al menos dos botes.

k. Obtener los nombres de les marines que alquilaron sólo un bote.

l. Obtener los nombres de les marines que alquilaron todos los botes.

m. Obtener los nombres de les marines que alquilaron todos los botes
verdes.

n. Obtener las fechas en que hay botes reservados.

o. Obtener las fechas en que están reservados todos los botes.

2. Dadas las siguientes relaciones
+
gusta(bebedore, cerveza)
+
frecuenta(bebedore, bar)
+
sirve(bar, cerveza)
+
--
Suponer que:

- Todas las cervezas son servidas en al menos un bar.

- Todes les bebedores frecuentan al menos un bar, y les gusta al menos
una cerveza.

- Todos los bares sirven al menos una cerveza.
--
+
Obtener mediante álgebra relacional:

a. Los nombres de todos los bares.

b. Los nombres de todes les bebedores.

c. Las cervezas que le gustan a Barney y que son servidas en el bar
Rockeria.

d. Los bares que sirven todas las cervezas que le gustan a Misato
Katsuragi.

e. Los bares que sirven todas las cervezas que le gustan a Misato
Katsuragi y a Ritsuko Akagi.
// Este ejercicio es muuucho muy rebuscado, mejor lo sacamos.
//f. Les bebedores que van a bares que sólo sirven cervezas que les
//gustan.

3. Dadas las siguientes relaciones
+
libro([underline]#id_libro#, titulo, autore, editorial)
+
socie([underline]#id_socie#, nombre, direccion, localidad)
+
prestamo([underline]#id_libro, id_socie, fecha#, cant_dias)
+
Obtener mediante álgebra relacional:

a. El nombre y la dirección de les socies que pidieron prestados a la
biblioteca, todos los libros escritos por Borges.

b. El id de les socies de Grand Bourg que nunca pidieron prestado un
libro de la editorial Sudamericana.

c. El título de los libros de la editorial Planeta que fueron prestados
tanto a socies de San Miguel como a socies de Los Polvorines.

d. Los préstamos realizados a socies de José C. Paz por más de 5 días, y
los realizados a socies de Bella Vista por más de 3 días. Se pide
mostrar el nombre de le socie, el título del libro y la fecha del
préstamo.

=== Parte II: SQL

1. Resolver mediante SQL, desde el ítem (1a) hasta el (1g), y el (1n) de
la primera parte.

2. (group by) Resolver mediante SQL, los ítems (1j) y (1k) de la primera
parte.

3. (subqueries) Resolver mediante SQL, los ítems (1h) y (1i) de la
primera parte.

4. (división) Resolver mediante SQL, los ítems (1l), (1m) y (1o) de la
primera parte.

5. Resolver mediante SQL todos los ítems del Ejercicio 2 de la primera
parte.

== Práctica 4

=== Parte I: Stored Procedures

1. Escribir una función que se llame `buscar_alumne()`, y que reciba un
número de legajo, y que devuelva el nombre y apellido de le alumne.

2. Escribir una función, `reservar_bote()`, que reciba como parámetros,
un `mid`, un `bid`, y una `fecha`, y que realice una reserva. Si el bote
solicitado no estuviera libre, se debe buscar otro bote libre del mismo
color y reservarlo. Suponer que siempre existe algún bote libre.

3. Escribir una función, `alquilaste_todos()` que reciba el `mid` de une
marine y que diga si alquiló todos los botes (`true` ó `false`).

4. Escribir una función, `materia_cursada_por_todes()`, que devuelva el
código de la materia cursada por todes les alumnes. Suponer que existe
una única materia que cumple lo solicitado.

5. Escribir una función `bares_con_cervezas_para_ambes()` que reciba dos
bebedores y que muestre los bares que sirven todas las cervezas que le
gustan a ambes bebedores.

=== Parte II: Triggers

1. Cada vez que se inserte une nueve bebedore en la tabla frecuenta, se
debe insertar a ese bebedore en la tabla gusta, asociade a la cerveza
Quilmes.

2. Si une marine tiene puntaje mayor ó igual a 100, se deben ingresar
todos sus datos en una nueva tabla marine_top con el mismo schema que la
tabla marine. El trigger debe dispararse tanto para insert, como para
update.

3. Cada vez que une marine alquile un barco, debe borrarse el registro
de la tabla reserva. Se supone que todes les marines primero reservan el
barco, y después lo alquilan.

4. Cada vez que une marine alquile todos los botes, insertar su datos en
la tabla cliente_vip (si todavía no está insertado en esa tabla).
